- mcp_clients/llms/anthropic.py
- mcp_clients/llms/base.py
- mcp_clients/llms/openai.py
- mcp_clients/mcp_client.py
- mcp_clients/requirements.txt
Support MCP resources in client.
> Add handling of resources.

- mcp_clients/base_bot.py
- mcp_clients/discord_bot.py
- mcp_clients/llms/base.py
- mcp_clients/slack/context.py
- mcp_clients/slack/message_handlers.py
- mcp_clients/slack_bot.py
- mcp_clients/web_bot.py
Create a web client with Fastapi.
> Create a web client.

- README.md
- fix broken discord and slack readme links
- update the discord community invite link
> docs(README.md):

- mcp_servers/.eslintignore
- mcp_servers/.eslintrc.js
- mcp_servers/.prettierignore
- mcp_servers/.prettierrc.json
- mcp_servers/firecrawl/.eslintrc.json
- mcp_servers/firecrawl_deep_research/.eslintrc.json
- mcp_servers/package-lock.json
- mcp_servers/package.json
- mcp_servers/postgres/.eslintrc.json
- mcp_servers/resend/.eslintrc.json
- mcp_servers/slack/.eslintrc.json
- mcp_servers/supabase/.eslintrc.json
- mcp_servers/tsconfig.json
> feat(mcp_server):Added linting for TS/JS

- mcp_servers/github/go.mod
- mcp_servers/github/go.sum
- mcp_servers/github/pkg/github/repositories.go
- mcp_servers/github/pkg/github/server.go
use graph QL instead of normal rest api (oldest first) to get recent star users
> github list star

- mcp_servers/google_slides/.env.example
- mcp_servers/google_slides/Dockerfile
- mcp_servers/google_slides/README.md
- mcp_servers/google_slides/requirements.txt
- mcp_servers/google_slides/server.py
This PR adds a new Google Slides MCP server implementation to the Klavis ecosystem. The server provides comprehensive access to Google Slides functionality through the Model Context Protocol (MCP), allowing AI agents to create and manipulate presentations programmatically.
- Create new Google Slides presentations with custom titles
- Add slides to existing presentations with title and content
- List all available presentations in user's Google Drive
- Retrieve detailed information about specific presentations
- Support for batch operations through the Google Slides API
- Extract and summarize text content from presentations
- Full MCP protocol compatibility with both SSE and StreamableHTTP transports
- Built using the standard Klavis MCP server pattern with proper tool registration
- Uses …
> Add google slides mcp server

- mcp-clients/src/mcp_clients/sse_client.py
- mcp-clients/uv.lock
- mcp_servers/gmail/Dockerfile
- mcp_servers/gmail/package-lock.json
- mcp_servers/gmail/package.json
- mcp_servers/gmail/src/index.ts
- mcp_servers/gmail/src/utl.ts
- mcp_servers/gmail/tsconfig.json
- mcp_servers/notion/LICENSE
- mcp_servers/notion/package.json
- mcp_servers/resend/package.json
> Add gmail server

- mcp_servers/google_docs/.env.example
- mcp_servers/google_docs/Dockerfile
- mcp_servers/google_docs/requirements.txt
- mcp_servers/google_docs/server.py
> Google Docs MCP Server

- mcp_servers/google_sheets/.env.example
- mcp_servers/google_sheets/Dockerfile
- mcp_servers/google_sheets/models.py
- mcp_servers/google_sheets/requirements.txt
- mcp_servers/google_sheets/server.py
- mcp_servers/google_sheets/utils.py
> Add google sheets

- examples/connect-mcp-server/requirements.txt
- examples/connect-mcp-server/script.py
> Add example

- mcp_servers/asana/Dockerfile
> update asana docker file

- mcp_servers/attio/index.ts
> fix and add more features for attio

- .github/workflows/python-sdk-release.yml
- fern/generators.yml
> Add action for fern sdk generation

- .github/workflows/python-sdk-release.yml
> add release step in action

- fern/overrides.yml
> update enum config for fern

- fern/openapi.json
- fern/overrides.yml
> override api key for fern sdk

- fern/generators.yml
- fern/overrides.yml
> customize sdk name

- examples/openai/Use_Klavis_with_OpenAI.ipynb
> update openai example 

- .github/workflows/typescript-sdk-release.yml
> add ts sdk workflow

- examples/openai/typescript/demo.ts
- examples/openai/typescript/package-lock.json
- examples/openai/typescript/package.json
> add ts sdk example with openai

- examples/crewai/Use_Klavis_with_CrewAI.ipynb
> add crewai

- examples/crewai/python/README.md
- examples/crewai/python/multi_service_crew.py
- examples/crewai/python/requirements.txt
> add python code for crew ai

- fern/README.md
- fern/openapi.json
> upgrade SDK

- mcp_servers/salesforce/server.py
- mcp_servers/salesforce/tools/accounts.py
- mcp_servers/salesforce/tools/base.py
- mcp_servers/salesforce/tools/cases.py
- mcp_servers/salesforce/tools/contacts.py
- mcp_servers/salesforce/tools/leads.py
- mcp_servers/salesforce/tools/opportunities.py
> salesforce tool optimize

- README.md
- examples/claude/Use_Klavis_with_Claude.ipynb
> rm default streamable_http

- examples/crewai/Salesforce_Gmail_CrewAI_Integration.ipynb
- examples/crewai/python/salesforce-gmail.py
> feat: add crewai demo

- mcp_servers/affinity/.env.example
- mcp_servers/affinity/Dockerfile
- mcp_servers/affinity/README.md
- mcp_servers/affinity/requirements.txt
- mcp_servers/affinity/server.py
- mcp_servers/affinity/tools/__init__.py
- mcp_servers/affinity/tools/base.py
- mcp_servers/affinity/tools/field_values.py
- mcp_servers/affinity/tools/list_entries.py
- mcp_servers/affinity/tools/lists.py
- mcp_servers/affinity/tools/notes.py
- mcp_servers/affinity/tools/opportunities.py
- mcp_servers/affinity/tools/organizations.py
- mcp_servers/affinity/tools/persons.py
> feat: add affinity

- docs/snippets/mcp-server-card/supabase-card.mdx
- docs/snippets/mcp-server-card/zendesk-card.mdx
> fix supabase and zendesk icon

- .github/workflows/mcp_clients_lint.yml
- .github/workflows/mcp_servers_lint.yml
- README.md
> rm lint workflow

- docs/documentation/introduction.mdx
> docs: add cards category

- docs/api-reference/mcp-server/get-auth-metadata.mdx
- docs/api-reference/openapi.json
- docs/docs.json
> feat: add get auth metadata api to docs

- docs/documentation/mcp-server/hubspot.mdx
- mcp_servers/hubspot/server.py
- mcp_servers/hubspot/tools/__init__.py
- mcp_servers/hubspot/tools/notes.py
> update: hubspot - add create note tool

- docs/documentation/oauth_white_label.mdx
> docs: update white label with SDK

- mcp_servers/affinity/requirements.txt
- mcp_servers/airtable/requirements.txt
- mcp_servers/asana/requirements.txt
- mcp_servers/clickup/requirements.txt
- mcp_servers/close/requirements.txt
- mcp_servers/confluence/requirements.txt
- mcp_servers/discord/requirements.txt
- mcp_servers/gong/requirements.txt
- mcp_servers/google_calendar/requirements.txt
- mcp_servers/google_docs/requirements.txt
- mcp_servers/google_drive/requirements.txt
- mcp_servers/google_sheets/requirements.txt
- mcp_servers/google_slides/requirements.txt
- mcp_servers/hubspot/requirements.txt
- mcp_servers/linear/requirements.txt
- mcp_servers/markitdown/requirements.txt
- mcp_servers/motion/requirements.txt
- mcp_servers/pandoc/requirements.txt
- mcp_servers/report_generation/requirements.txt
- mcp_servers/salesforce/requirements.txt
- mcp_servers/stripe/requirements.txt
- mcp_servers/youtube/requirements.txt
> upgrade mcp denpendency

- mcp_servers/google_calendar/server.py
> update: gcalendar attendee

- mcp_servers/affinity/server.py
> fix: Affinity get notes json error

- mcp_servers/linkedin/server.py
> fix: linkedin prod issue

- mcp_servers/linkedin/Dockerfile
> fix: update linkedin dockerfile

- mcp_servers/linkedin/server.py
> fix: linkedin tool issue

- docs/documentation/mcp-server/linkedin.mdx
> doc: update linkedin tool

- docs/documentation/mcp-server/linkedin.mdx
> Revert "doc: update linkedin tool"

- docs/documentation/mcp-server/linkedin.mdx
> doc: update doc

- mcp_servers/google_calendar/server.py
> update: gcalendar create event support send notification

- mcp_servers/google_calendar/server.py
> update: support google meet for gcalendar

- mcp_servers/notion/Dockerfile
> fix: update dockerfile for notion

- docs/knowledge-base/oauth/xero.mdx
> doc: xero doc update

- docs/api-reference/openapi.json
> update openapi json

- MCP_SERVER_GUIDE.md
Improve MCP_SERVER_GUIDE
- Added important resources for understanding MCP architecture and operational modes.
- Included guidelines for documenting functions with AI prompt words, titles, and parameter usage.
- Improved clarity and comprehensiveness of the guide to aid contributors in developing and testing MCP
> docs/MCP_SERVER_GUIDE: Additional Resources and Documentation Guidelines

- docs/docs.json
- docs/documentation/klavis-unified-mcp-server.mdx
> Doc: Add tutorial to use the unified mcp server.

- docs/documentation/klavis-unified-mcp-server.mdx
> Doc: Fix unified MCP server docs.

- mcp_servers/gong/server.py
> Fix: Fix port of gong.

- docs/api-reference/openapi.json
> update: upgrade openapi and sdk

- docs/api-reference/user/delete-user.mdx
> doc: Add delete user endpoint

- docs/api-reference/openapi.json
- docs/docs.json
> doc: update api

- docs/documentation/develop-with-ai.mdx
> doc: append develop with AI option

- mcp_servers/quickbooks/.env.example
- mcp_servers/quickbooks/Dockerfile
- mcp_servers/quickbooks/server.py
Fix Dockerfile and change port from 5001 to 5000
> fix/quickbooks: fix Dockerfile

- mcp_servers/quickbooks/session_manager.py
> Fix: Fix quickbook access token.

- mcp_servers/openrouter/Dockerfile
Change Dockerfile to adapt Google Build
> fix/openrouter: fix Google Build deploy

- docs/knowledge-base/oauth_app/oauth-scopes.mdx
> Doc: Add quickbooks scope.

- mcp_servers/attio/index.ts
> Feat: Add create task and support search by record id in Attio.

- mcp_servers/coinbase/README.md
- mcp_servers/gmail/package-lock.json
- mcp_servers/gmail/package.json
- mcp_servers/gmail/src/index.ts
- mcp_servers/gmail/src/utl.ts
> fix : security

- mcp_servers/notion/server.py
- mcp_servers/notion/tools/pages.py
The current notion create_page tool is bad design, this PR - 
1. 
> fix: notion create page tool update

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
Add GitHub issues template
Tested in https://github.com/xz-dev/klavis/issues/new/choose
> feat/github: Add GitHub issues template

- docs/api-reference/mcp-server/create-a-self-hosted-mcp-server-instance.mdx
- docs/api-reference/openapi.json
- docs/docs.json
> Doc: Update docs with new api for self hosted versions.

- docs/api-reference/openapi.json
> Doc: Fix openapi json.

- .github/workflows/mcp-servers-build.yml
Add auto docker image build CI for MCP server
1. When new commit pushed to main branch, and the change in mcp_servers/
2. Manually run Action
Tested in https://github.com/xz-dev/klavis
> ci/github: add docker image build

- mcp_servers/google_slides/Dockerfile
- mcp_servers/hubspot/requirements.txt
- mcp_servers/tavily/Dockerfile
fix 3 mcp servers docker image build fail
https://github.com/Klavis-AI/klavis/pull/325
Run docker build locally
> fix/ci: fix 3 mcp servers docker image build fail

- docs/knowledge-base/introduction.mdx
introduction.mdx error fix
[Screencast From 2025-08-17 16-07-52.webm](https://github.com/user-attachments/assets/9c1e3ab9-1bdf-49af-8f27-3f01e840559e)
> docs(introduction.mdx):  introduction.mdx error fix

- mcp_servers/exa/server.py
- mcp_servers/freshdesk/Dockerfile
> fix dockerfile

- mcp_servers/shopify/package-lock.json
> fix shopify package json

- docs/api-reference/mcp-server/set-auth-token.mdx
- docs/api-reference/mcp-server/set-authentication-data.mdx
- docs/api-reference/openapi.json
- docs/docs.json
- docs/documentation/mcp-server/affinity.mdx
- docs/documentation/mcp-server/brave_search.mdx
- docs/documentation/mcp-server/firecrawl-deep-research.mdx
- docs/documentation/mcp-server/firecrawl-web-search.mdx
- docs/documentation/mcp-server/gong.mdx
- docs/documentation/mcp-server/heygen.mdx
- docs/documentation/mcp-server/moneybird.mdx
- docs/documentation/mcp-server/motion.mdx
- docs/documentation/mcp-server/openrouter.mdx
- docs/documentation/mcp-server/plai.mdx
- docs/documentation/mcp-server/postgres.mdx
- docs/documentation/mcp-server/resend.mdx
- docs/documentation/mcp-server/supabase.mdx
- docs/documentation/mcp-server/whatsapp.mdx
- docs/documentation/sdk/typescript.mdx
> Update auth doc to use the new set-auth.

- docs/knowledge-base/oauth_app/slack.mdx
> update slack scope

- docs/documentation/mcp-server/slack.mdx
- docs/knowledge-base/oauth_app/slack.mdx
- mcp_servers/slack/server.py
- mcp_servers/slack/user_tools/__init__.py
- mcp_servers/slack/user_tools/channels.py
> slack: add invite tool

- mcp_servers/freshdesk/server.py
- mcp_servers/notion/server.py
> Fix: Fix auth header error.

- mcp_servers/attio/index.ts
- mcp_servers/exa/server.py
- mcp_servers/firecrawl/index.ts
- mcp_servers/firecrawl_deep_research/index.ts
- mcp_servers/freshdesk/server.py
- mcp_servers/google_jobs/server.py
- mcp_servers/postgres/index.ts
- mcp_servers/quickbooks/session_manager.py
- mcp_servers/resend/index.ts
- mcp_servers/salesforce/server.py
- mcp_servers/tavily/server.py
- mcp_servers/whatsapp/index.ts
> Fix auth issues.

- mcp_servers/tavily/server.py
> fix tavily.

- mcp_servers/hubspot/server.py
- mcp_servers/hubspot/tools/__init__.py
- mcp_servers/hubspot/tools/base.py
- mcp_servers/hubspot/tools/tasks.py
> add hubspot tasks

- mcp_servers/mailchimp/Dockerfile
> fix/mailchimp: fix Dockerfile

- docs/knowledge-base/introduction.mdx
Adds Claude Desktop and Windsurf file to Introduction.mdx
> docs(Claude Desktop and Windsurf): Add to Introduction.mdx

- README.md
Use env value without manually replace.
> docs/readme: update docker example use env value

- README.md
> docs/readme: add /mcp path note

- README.md
> fix readme.

- mcp_servers/linear/server.py
- mcp_servers/linear/tools/issues.py
> fix linear

- docs/documentation/introduction.mdx
Small typo in the Introduction.mdx
> fix: typo in the intro section

- mcp_servers/wordpress/index.ts
> add category 2

- .github/workflows/mcp-servers-build.yml
https://github.com/Klavis-AI/klavis/pull/417
> fix/ci: fix mcp-servers-build

- docs/api-reference/openapi.json
> upgrade openapi

- mcp_servers/quickbooks/session_manager.py
> fix quickbooks.

- docs/api-reference/openapi.json
> add zendesk

- docs/api-reference/openapi.json
> upgrade api

- mcp_servers/google_drive/server.py
Add 2 tools: empty_trash and create_shared_drive
> feat/google_drive: add empty_trash and create_shared_drive

- docs/documentation/quickstart.mdx
LlamaIndex Code to connect Klavis Strata to Multi-app and Individual-app Integrations.
Tested with Claude and Terminal.
Working Below:
1. Individual-app Integration screenshot: 
2. Multi-app Integration screenshot:
> Docs(LlamaIndex): LlamaIndex Docs for Multi-app and Individual-app Integrations

- open-strata/README.md
- open-strata/src/strata/utils/shared_search.py
> Fix code and doc.

- docs/documentation/concepts/strata.mdx
> add tool info

- mcp_servers/shopify/index.ts
> fix spotify

- docs/documentation/concepts/strata.mdx
> quick fix doc

- fern/generators.yml
> ts sdk fix

- docs/api-reference/calcom-oauth/calcom-client-credentials-auth.mdx
- mcp_servers/mixpanel/tools/base.py
> Increase timeout.

- mcp_servers/gmail/src/index.ts
> Use json results.

- docs/api-reference/openapi.json
- examples/openai-klavis/strata-python/requirements.txt
> sdk upgrade

- docs/api-reference/openapi.json
Update API specifications by running fern api update.
> Update API specifications with fern api update
